SELECT
	COUNSEL_BNO, COUNSEL_TITLE, COUNSEL_WRITER,
	DATE_FORMAT(COUNSEL_REGDATE, "%Y-%m-%d")
FROM COUNSEL_INFO ORDER BY 4 DESC;

SELECT
	COUNSEL_BNO, COUNSEL_TITLE, COUNSEL_CONTENT, COUNSEL_WRITER,
	DATE_FORMAT(COUNSEL_REGDATE, "%Y-%m-%d %H:%i:%s") COUNSEL_REGDATE
FROM COUNSEL_INFO
WHERE COUNSEL_BNO = 27;